name: Build Plugin fix

on:
  push:
    branches:
      - '*'
#  pull_request:
#    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      CI: true
      CI_BUILD_VERSION: 1.4.21

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build 2025.1.2
        env:
          IDEA_VER: 251
        run: ./gradlew buildPlugin

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: v${{ env.CI_BUILD_VERSION }}
          path: build/distributions/*.zip
